version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.port=19200
    ports:
      - "19200:19200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19200"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  app:
    image: openjdk:17-jdk
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./src/main/resources/Files:/app/files   # لمجلد الملفات
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8085:8085"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:19200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FILES_DIRECTORY=/app/files
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

volumes:
  esdata:
  redisdata:

